### PR TITLE
fix!: renamed args to args-file to make it less confusing

### LINKED ISSUE #2: rename args to args-file to avoid confusion whether its Kurtosis CLI args or args for enclave

### PR DESCRIPTION
**Pull request by h4ck3rk3y**

### CODE REVIEW

File: commit.sh [hunk 1]
```diff
@@ -1,7 +0,0 @@
-git add .
```
Comment (leoporoli) [inline commit.sh:1]: just shouting out in case of accidental remotion @h4ck3rk3y

**Review by leoporoli — APPROVED** [review]

File: commit.sh (hunk 1 above)
Comment (h4ck3rk3y) [reply commit.sh:1]: oh i removed this as i had added this script only for a fast dev workflow while figuring out how actions work 😅 
now will tag and release appropriately
